---
- name: Install fonts from pacman
  become: true
  pacman:
    name: ttf-croscore, ttf-font-awesome, ttf-fira-code, noto-fonts-emoji
    state: latest

- name: Install fonts from AUR
  aur:
    name:
      - ttf-ms-fonts
      - ttf-google-fonts-git
      - ttf-symbola
    skip_installed: true
