---
# - name: Get best pacman mirrors
#   become: true
#   shell: pacman-mirrors --fasttrack

- name: Update pacman packages
  become: true
  pacman:
    # update_cache: yes
    upgrade: yes

- name: Install pacman packages
  become: true
  pacman:
    name: "{{pacman_packages}}"
    state: latest
