---
- name: Install gdebi
  become: true
  apt:
    name: gdebi
    state: latest

- name: Download hyper.js deb file
  shell: wget https://releases.hyper.is/download/deb

- name: Install hyper.js
  become: true
  shell: gdebi -n deb

- name: Remove downloaded file
  shell: rm deb

- name: Add configuration file
  copy:
    src: ../config/ubuntu.hyper.js
    dest: $HOME/.hyper.js