---
- import_tasks: apt.yml
- import_tasks: elementary-tweaks.yml
- import_tasks: fonts.yml
- import_tasks: git.yml
- import_tasks: dotfiles.yml
- import_tasks: nodejs.yml
- import_tasks: npm.yml
- import_tasks: chrome.yml
- import_tasks: vscode.yml
- import_tasks: hyper.yml
- import_tasks: vagrant.yml
- import_tasks: dotnet.yml
- import_tasks: remmina.yml
- import_tasks: micro.yml
- import_tasks: franz.yml
- import_tasks: ulauncher.yml
- import_tasks: googleplaymusic.yml
- import_tasks: nomachine.yml