pacman_packages:
  - git
  - feh
  - compton
  - polybar
  - vim
  - xclip
  - shellcheck
  - virtualbox
  - gimp
  - libreoffice-fresh
  - aws-cli
  - bash-completion
  - snapd
  - go
  - hugo
  - rofi
  - vifm
  - cowsay
  - flameshot
  - lastpass-cli
  - python-pip
  - xcursor-neutral
  - ncmpcpp
  - mpc
  - xorg-xbacklight
  - devilspie
  - calcurse
  - python-oauth2client
  - python-httplib2
  - mpv
  - neofetch
  - jq
  - qalculate-gtk
  - scribus
  - yarn

node_packages:
  - vtop
  - typescript
  - eslint
  - prettier
  - create-react-app
  - '@angular/cli'
  - '@vue/cli'
  - gulp

unsafe_node_packages:
  - backstopjs

git_repos:
  - dotfiles
